# Generated by Django 4.1.4 on 2022-12-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_text',
            field=models.TextField(default='vacio'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tittle',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
    ]
