# Generated by Django 4.1.4 on 2022-12-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_about_text_alter_home_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about_text',
            field=models.TextField(),
        ),
    ]
